version: "3.8"
services:
  postgis:
    image: "mdillon/postgis"
    ports:
      - "5432:5432"
    volumes:
      - YOUR_HOST_DIRECTORY:/var/lib/postgresql
  geoserver:
    image: "kartoza/geoserver"
    ports:
      - "8080:8080"
    volumes:
      - YOUR_HOST_DIRECTORY:/opt/geoserver/data_dir
    depends_on:
      - postgis
