version: "3.8"
services:
  postgis:
    image: "mdillon/postgis"
    ports:
      - "5432:5432"
    volumes:
      - YOUR_HOST_DIRECTORY/postgres_data/data:/var/lib/postgresql/data
  geoserver:
    image: "kartoza/geoserver"
    ports:
      - "8080:8080"
    volumes:
      - YOUR_HOST_DIRECTORY/geoserver_data:/opt/geoserver/data_dir
    depends_on:
      - postgis
networks:
  default:
    external:
      name: gist604b
